### ISSUE TITLE
Need a little more usage information. 

### ISSUE THREAD

**Issue by jimmckeeth** [yunkot/HeaderParser#1]
When running it gives the following usage information, but I'll still not clear on how to use it 

> Header Parser syntax:
>   headerparser.exe (file.h) (header.pas) (output.pas)

I expect that **file.h** is the C header input, and **output.pas** is the Pascal file output, but not sure what **header.pas** needs to be. Is this a secondary output file, or a secondary input file?

**Comment by yunkot** [comment]
**file.h** is indeed the source header file, **output.pas** is the resulting file and **header.pas** will be prepended to the resulting output file.

This tool has been developed many years ago and then was adapted specifically to translate Afterwarp's framework headers (and previously, it successfully translated DirectX 10/11 and other Windows API headers for Asphyre/PXL). It's client interface could certainly use some improvements, maybe even switching from console to GUI-based. Any assistance and/or pull requests are welcome.
